server:
  port: 8080

spring:
  sql.init.mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/ewm
    username: ewm
    password: ewm
  jpa:
    properties:
      show_sql: true

logging:
  level:
    root: INFO
    ru.practicum: DEBUG
    org:
      type.descriptor.sql.BasicBinder: INFO
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: INFO
        transaction: INFO
        transaction.interceptor: INFO