server:
  port: 9090

spring:
  sql.init.mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats
    username: stats
    password: stats
  jpa:
    properties:
      show_sql: true

logging:
  level:
    root: INFO
    ru.practicum: DEBUG
    org:
      type.descriptor.sql.BasicBinder: INFO
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: INFO
        transaction: INFO
        transaction.interceptor: INFO